### ISSUE TITLE
getting error while building for ios

### ISSUE THREAD

**Issue by muskanstegowl** [8fdafs2/flutter_raw_sound#2]
Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
    [!] CocoaPods could not find compatible versions for pod "raw_sound":
      In Podfile:
        raw_sound (from `.symlinks/plugins/raw_sound/ios`)

    Specs satisfying the `raw_sound (from `.symlinks/plugins/raw_sound/ios`)` dependency were found, but they required a higher minimum deployment target.

**Comment by 8fdafs2** [comment]
I think you might need to set/increase the minimum iOS version, please check the README.md first, and a quick search gives me this: [https://github.com/roughike/flutter_twitter_login/issues/26](https://github.com/roughike/flutter_twitter_login/issues/26) which likely provides solutions for you.

**Comment by muskanstegowl** [comment]
thank you i got my solution
