### ISSUE TITLE
iOS 14 requirement

### ISSUE THREAD

**Issue by lukepighetti** [8fdafs2/flutter_raw_sound#5]
What's driving the iOS 14 requirement? What would it take to drop it down to iOS 12?

**Comment by 8fdafs2** [comment]
The swift code uses Apple's Unified Logging System, which requires iOS 14 and above. I'm afraid that you may need to modify the code by yourself to implement another logging mechanism to lower the iOS version requirement.

**Comment by lukepighetti** [comment]
Is Apple's Unified Logging System a requirement for this package?

**Comment by 8fdafs2** [comment]
> Is Apple's Unified Logging System a requirement for this package?

I don't think so, it's just a way to log (human-readable) messages mainly for debugging purposes. The package should work properly w/o it.

**Comment by 8fdafs2** [comment]
I am closing this issue.
